### ISSUE TITLE
Show test results discord channel  (also failure channel ) in discord with log links

### ISSUE THREAD

**Issue by v-stickykeys** [3box/ceramic-integration-tests#19]

**Comment by valmack** [comment]
Will do this as a link to the aws cloudwatch logs

**Comment by v-stickykeys** [comment]
@mahendra3web example on constructing url to logs. This is used for messages in the warnings-ceramic channel on discord

https://github.com/ceramicnetwork/ceramic-anchor-service/blob/develop/runner/helpers.js
